services:
  nginx:
    image: kauech/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_MAP_HOST_AS_TARGET: |
        default http://localhost:8080;
      NGINX_FORCE_HTTPS: "true"
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
