services:

  # nginx-http:
  #   build:
  #     context: .
  #     target: http
  #   image: kauech/nginx-http:latest
  #   restart: no

  nginx:
    build:
      context: .
      target: self-signed
    image: kauech/nginx:latest
    restart: no
    environment:
      NGINX_MAP_HOST_AS_TARGET: |
        default http://localhost:8080;

    volumes:
      - ./data/letsencrypt:/etc/letsencrypt

  nginx-cloudflare:
    build:
      context: .
      target: cloudflare
    image: kauech/nginx-cloudflare:latest
    restart: no